name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs at midnight
  workflow_dispatch: # Allows manual run
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Use the secret you already created
          token: ${{ secrets.GH_TOKEN }}
          
          # Options
          user: R-Valdez
          template: classic
          base: header, community, repositories, metadata
          config_timezone: America/Mexico_City # Adjust if needed
          
          # This saves the file as "github-metrics.svg" in your repo
          filename: github-metrics.svg
