name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:      

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: R-Valdez
          template: classic
          
          # 1. UI Settings
          base: "" 
          config_timezone: America/Los_Angeles
          
          # 2. Language Logic (Keeping your actual languages)
          plugin_languages: yes
          # We ONLY ignore the stuff you didn't intentionally write:
          plugin_languages_ignored: >-
            typescript, makefile, shell, java
          
          plugin_languages_limit: 0
          plugin_languages_categories: programming, markup
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          
          # 3. Output
          filename: github-metrics.svg
